### ISSUE TITLE
Eslint 범위 수정 및 추가할 것

### ISSUE THREAD

**Issue by CitrusSoda** [BestSprinters/i-Konnect#4]
### ⚠ 무슨 문제가 발생했나요?

루트 폴더에도 Eslint 규칙이 적용되어 config 파일에 영향을 끼칩니다.

### 📄 에러 내용 및 로그

#2 의 [tailwind.config.js](https://github.com/Darkthos/i-Konnect/pull/2/files/18939b0efb67ea81707e3b3f9bc4c5a18277f3bb#diff-ddc1067f080930bc48865f4660316a14b21bbc9f9ba85975ce8479342b983d2e) 에서 확인하였습니다.

### 🛠 수정해야 할 사항

package.json의 lint-staged 부분을 "src/**/*.{js,jsx,ts,tsx}" 로 소스 폴더로 제한해야할 것 같습니다.

### 🌊 기타 사항

수정하면서 .eslintrc.cjs의 eslint 규칙에 airbnb/hooks추가하고 eslint와 prettier 충돌을 피하기 위해 eslint-config-prettier 적용하면 좋을 것 같습니다!

**Comment by heony704** [comment]
너무 좋은 의견입니다
